/*
 * This source file was generated by the Gradle 'init' task
 */
package animali;

import java.util.List;

interface Animale {
    void emettiVerso();
    void muoviti();
}
abstract class AnimaleBase implements Animale {
    private String nome;
    
    public AnimaleBase(String nome) {
        this.nome = nome;
    }

    public String getNome() {
        return nome;
    }
}
class Cane extends AnimaleBase {
    public Cane(String nome) {
        super(nome);
    }

    @Override
    public void emettiVerso() {
        System.out.println(getNome() + " abbaia.");
    }

    @Override
    public void muoviti() {
        System.out.println(getNome() + " corre.");
    }
}
class Gatto extends AnimaleBase {
    public Gatto(String nome) {
        super(nome);
    }

    @Override
    public void emettiVerso() {
        System.out.println(getNome() + " miagola.");
    }

    @Override
    public void muoviti() {
        System.out.println(getNome() + " salta.");
    }
}
public class GestioneAnimali {
    public static void main(String[] args) {
        List<Animale> animali = List.of(
            new Cane("Colonnello"),
            new Gatto("Sergente Tibs")
        );
        for (Animale animale : animali) {
            animale.emettiVerso();
            animale.muoviti();
        }
    }
}
