/*
 * This source file was generated by the Gradle 'init' task
 */
package calendario;
import java.util.ArrayList;
import java.util.Scanner;

class Appuntamento {
    private String data;        // formato: "gg/mm/aaaa"
    private String ora;         // formato: "hh:mm"
    private String descrizione;

    public Appuntamento(String data, String ora, String descrizione) {
        this.data = data;
        this.ora = ora;
        this.descrizione = descrizione;
    }

    public String getData() {
        return data;
    }

    public String getOra() {
        return ora;
    }

    public String getDescrizione() {
        return descrizione;
    }

    @Override
    public String toString() {
        return "Data: " + data + ", Ora: " + ora + ", Descrizione: " + descrizione;
    }
}

public class App {
    public static void main(String[] args) {
        ArrayList<Appuntamento> appuntamenti = new ArrayList<>();
        Scanner scanner = new Scanner(System.in);

        while (true) {
            System.out.println("\n1. Aggiungi appuntamento");
            System.out.println("2. Visualizza appuntamenti");
            System.out.println("3. Esci");
            System.out.print("Scegli un'opzione: ");
            int scelta = scanner.nextInt();
            scanner.nextLine(); // consuma il newline

            if (scelta == 1) {
                System.out.print("Inserisci la data (gg/mm/aaaa): ");
                String data = scanner.nextLine();
                System.out.print("Inserisci l'ora (hh:mm): ");
                String ora = scanner.nextLine();
                System.out.print("Inserisci la descrizione: ");
                String descrizione = scanner.nextLine();
                appuntamenti.add(new Appuntamento(data, ora, descrizione));
                System.out.println("Appuntamento aggiunto!");
            } else if (scelta == 2) {
                if (appuntamenti.isEmpty()) {
                    System.out.println("Nessun appuntamento presente.");
                } else {
                    System.out.println("Appuntamenti:");
                    for (Appuntamento a : appuntamenti) {
                        System.out.println(a);
                    }
                }
            } else if (scelta == 3) {
                System.out.println("Uscita...");
                break;
            } else {
                System.out.println("Opzione non valida.");
            }
        }

        scanner.close();
    }
}
