/*
 * This source file was generated by the Gradle 'init' task
 */
package gestionemagazzino;

import java.util.HashMap;

class Magazzino<T>{
    private HashMap<String, T> magazzino = new HashMap<>();
    public void add(String oggetto, T quantita) {
        magazzino.put(oggetto, quantita);
    }
    public void remove(String oggetto) {
        magazzino.remove(oggetto);
    }
    public T get(String oggetto) {
        return magazzino.get(oggetto);
    }
}
public class App {

    public static void main(String[] args) {
        Magazzino<Integer> magazzino = new Magazzino<>();
        magazzino.add("Penne", 100);
        magazzino.add("Matite", 200);
        magazzino.add("Quaderni", 50);

        System.out.println("Quantità di penne: " + magazzino.get("Penne"));
        System.out.println("Quantità di matite: " + magazzino.get("Matite"));
        System.out.println("Quantità di quaderni: " + magazzino.get("Quaderni"));

        magazzino.remove("Matite");
        System.out.println("Quantità di matite dopo rimozione: " + magazzino.get("Matite"));
        magazzino.add("Matite", 150);
        System.out.println("Quantità di matite dopo aggiunta: " + magazzino.get("Matite"));
    }
}