/*
 * This source file was generated by the Gradle 'init' task
 */
package musica;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Scanner;

class Canzone implements Serializable {
    private String titolo;
    private String artista;
    private int durata; // durata in secondi

    public Canzone(String titolo, String artista, int durata) {
        this.titolo = titolo;
        this.artista = artista;
        this.durata = durata;
    }

    public String getTitolo() { return titolo; }
    public String getArtista() { return artista; }
    public int getDurata() { return durata; }

    @Override
    public String toString() {
        return titolo + " - " + artista + " (" + durata + "s)";
    }
}


public class App {
    private static final String FILE_NAME = "playlist.ser";
    
    private static void salvaPlaylist(ArrayList<Canzone> playlist) {
        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(FILE_NAME))) {
            oos.writeObject(playlist);
        } catch (IOException e) {
            System.out.println("Errore nel salvataggio: " + e.getMessage());
        }
    }

    private static ArrayList<Canzone> caricaPlaylist() {
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream(FILE_NAME))) {
            return (ArrayList<Canzone>) ois.readObject();
        } catch (Exception e) {
            return new ArrayList<>();
        }
    }
    public static void main(String[] args) {
        ArrayList<Canzone> playlist = caricaPlaylist();

        Scanner scanner = new Scanner(System.in);
        while (true) {
            System.out.println("\n1. Aggiungi canzone\n2. Visualizza playlist\n3. Salva playlist\n4. Carica playlist\n5. Esci");
            System.out.print("Scelta: ");
            int scelta = scanner.nextInt();
            scanner.nextLine(); // consuma newline

            switch (scelta) {
                case 1:
                    System.out.print("Titolo: ");
                    String titolo = scanner.nextLine();
                    System.out.print("Artista: ");
                    String artista = scanner.nextLine();
                    System.out.print("Durata (in secondi): ");
                    int durata = scanner.nextInt();
                    scanner.nextLine();
                    playlist.add(new Canzone(titolo, artista, durata));
                    break;
                case 2:
                    if (playlist.isEmpty()) {
                        System.out.println("Playlist vuota.");
                    } else {
                        for (Canzone c : playlist) {
                            System.out.println(c);
                        }
                    }
                    break;
                case 3:
                    salvaPlaylist(playlist);
                    System.out.println("Playlist salvata.");
                    break;
                case 4:
                    playlist = caricaPlaylist();
                    System.out.println("Playlist caricata.");
                    break;
                case 5:
                    salvaPlaylist(playlist);
                    System.out.println("Arrivederci!");
                    return;
                default:
                    System.out.println("Scelta non valida.");
            }
        }
    }

    
}
