/*
 * This source file was generated by the Gradle 'init' task
 *
 */
package cinema;

import java.util.ArrayList;

class Sala{
    private int numeroSala;
    private int postiDisponibili;
    public Sala(int numeroSala, int postiDisponibili){
        this.numeroSala = numeroSala;
        this.numeroPosti = numeroPosti;
        this.postiDisponibili = numeroPosti;
    }
    public int getPosti(){
        return postiDisponibili;
    }
    public void setPosti(int posti){
        this.postiDisponibili = posti;
    }
}
class Film{
    private String titolo;
    private String orario;
    private int sala;
    public Film(String titolo, String orario, int sala){
        this.titolo = titolo;
        this.orario = orario;
        this.sala = sala;
    }
    public String getTitolo(){
        return titolo;
    }
    public String getOrario(){
        return orario;
    }
    public int getSala(){
        return sala;
    }
}
class Prenotazione{
    private Film film;
    private Sala sala;
    public Prenotazione(Film film, Sala sala){
        this.film = film;
        this.sala = sala;
    }
    public void prenotaPosti(int posti){
        if(sala.getPosti() >= posti){
            sala.setPosti(sala.getPosti() - posti);
            System.out.println("Prenotazione effettuata con successo");
        }else{
            System.out.println("Posti non disponibili");
        }
    }
}
public class App {

    public static void main(String[] args) {
        ArrayList<Sala> sale = new ArrayList<>();
        ArrayList<Film> film = new ArrayList<>();
        sale.add(new Sala(1, 100));
        sale.add(new Sala(2, 50));
        film.add(new Film("L'uomo che venne dalla Terra", "20:00", 1));
        film.add(new Film("I sogni segreti di Walter Mitty", "22:00", 2));
        System.out.println("Benvenuto nel sistema di prenotazione cinema!");
        System.out.println("Seleziona un film:");
        for (int i = 0; i < film.size(); i++) {
            System.out.println((i + 1) + ". " + film.get(i).getTitolo() + " - " + film.get(i).getOrario());
        }
        int filmScelto = 1; // Simulazione di selezione film
        System.out.println("Hai selezionato: " + film.get(filmScelto - 1).getTitolo());
        System.out.println("Quel film è in sala " + film.get(filmScelto - 1).getSala());
        System.out.println("Posti disponibili: " + sale.get(film.get(filmScelto - 1).getSala() - 1).getPosti());
        System.out.println("Quanti posti vuoi prenotare?");
        int postiPrenotati = 2; // Simulazione di prenotazione
        Prenotazione prenotazione = new Prenotazione(film.get(filmScelto - 1), sale.get(film.get(filmScelto - 1).getSala() - 1));
        prenotazione.prenotaPosti(postiPrenotati);
        System.out.println("Hai prenotato " + postiPrenotati + " posti per il film " + film.get(filmScelto - 1).getTitolo());
        System.out.println("Posti disponibili dopo la prenotazione: " + sale.get(film.get(filmScelto - 1).getSala() - 1).getPosti());
        
    }
}
