/*
 * This source file was generated by the Gradle 'init' task
 */
package biblio;

import java.util.ArrayList;

abstract class MaterialeBibliotecario {
    private String titolo;
    private String autore;
    private int annoPubblicazione;

    public MaterialeBibliotecario(String titolo, String autore, int annoPubblicazione) {
        this.titolo = titolo;
        this.autore = autore;
        this.annoPubblicazione = annoPubblicazione;
    }
}
class Libro extends MaterialeBibliotecario implements Prestabile {
    private String isbn;
    private int numeroPagine;
    private boolean inPrestito = false;

    public Libro(String titolo, String autore, int annoPubblicazione, String isbn, int numeroPagine) {
        super(titolo, autore, annoPubblicazione);
        this.isbn = isbn;
        this.numeroPagine = numeroPagine;
    }

    @Override
    public void presta() {
        if (!inPrestito) {
            inPrestito = true;
            System.out.println("Libro '" + isbn + "' prestato.");
        } else {
            System.out.println("Libro '" + isbn + "' già in prestito.");
        }
    }

    @Override
    public void restituisci() {
        if (inPrestito) {
            inPrestito = false;
            System.out.println("Libro '" + isbn + "' restituito.");
        } else {
            System.out.println("Libro '" + isbn + "' non era in prestito.");
        }
    }
}
class Rivista extends MaterialeBibliotecario implements Prestabile {
    private String issn;
    private int numeroPagine;
    private boolean inPrestito = false;
    public Rivista(String titolo, String autore, int annoPubblicazione, String issn, int numeroPagine) {
        super(titolo, autore, annoPubblicazione);
        this.issn = issn;
        this.numeroPagine = numeroPagine;
    }
    @Override
    public void presta() {
        if (!inPrestito) {
            inPrestito = true;
            System.out.println("Rivista '" + issn + "' prestato.");
        } else {
            System.out.println("Rivista '" + issn + "' già in prestito.");
        }
    }

    @Override
    public void restituisci() {
        if (inPrestito) {
            inPrestito = false;
            System.out.println("Rivista '" + issn + "' restituito.");
        } else {
            System.out.println("Rivista '" + issn + "' non era in prestito.");
        }
    }
}
interface Prestabile {
    void presta();
    void restituisci();
}
public class App {

    public static void main(String[] args) {
        ArrayList<MaterialeBibliotecario> materiali = new ArrayList<>();
        materiali.add(new Libro("Il Signore degli Anelli", "J.R.R. Tolkien", 1954, "978-0261102385", 1216));
        materiali.add(new Rivista("National Geographic", "National Geographic Society", 1888, "0027-9358", 100));
        materiali.add(new Libro("1984", "George Orwell", 1949, "978-0451524935", 328));
        materiali.add(new Rivista("TIME", "Henry Luce", 1923, "0040-781X", 50));
        materiali.add(new Libro("Il Codice Da Vinci", "Dan Brown", 2003, "978-0307474278", 489));
        materiali.add(new Rivista("Scientific American", "Scientific American, Inc.", 1845, "0036-8733", 80));

        // Gestione prestito e restituzione
        for (MaterialeBibliotecario materiale : materiali) {
            if (materiale instanceof Prestabile) {
                Prestabile prestabile = (Prestabile) materiale;
                prestabile.presta();
                prestabile.restituisci();
            } else {
                System.out.println("Questo materiale non è prestabile.");
            }
        }
    }
}
