/*
 * This source file was generated by the Gradle 'init' task
 */
package prenotazione;
interface Prenotabile {
    void prenota();
    void cancella();
}
class Hotel implements Prenotabile {
    private String nome;
    private int stelle;
    private double prezzo;
    private int stanzeDisponibili;

    public Hotel(String nome, int stelle, double prezzo, int stanzeDisponibili) {
        this.nome = nome;
        this.stelle = stelle;
        this.prezzo = prezzo;
    }
    public void prenota() {
        System.out.println("Prenotazione hotel: " + nome);
        stanzeDisponibili=stanzeDisponibili-1;
    }
    public void cancella() {
        System.out.println("Cancellazione hotel: " + nome);
        stanzeDisponibili=stanzeDisponibili+1;
    }
}
class Volo implements Prenotabile {
    private String compagnia;
    private String partenza;
    private String arrivo;
    private int postiDisponibili;

    public Volo(String compagnia, String partenza, String arrivo, int postiDisponibili) {
        this.compagnia = compagnia;
        this.partenza = partenza;
        this.arrivo = arrivo;
    }
    public void prenota() {
        System.out.println("Prenotazione volo: " + compagnia);
        postiDisponibili=postiDisponibili-1;
    }
    public void cancella() {
        System.out.println("Cancellazione volo: " + compagnia);
        postiDisponibili=postiDisponibili+1;
    }
}

public class App {

    public static void main(String[] args) {
        Hotel hotel = new Hotel("Hotel Roma", 4, 150.0, 10);
        Volo volo = new Volo("Alitalia", "Roma", "Milano", 20);
        Prenotabile[] prenotabili = {hotel, volo};
        for (Prenotabile prenotabile : prenotabili) {
            prenotabile.prenota();
        }
        for (Prenotabile prenotabile : prenotabili) {
            prenotabile.cancella();
        }
        System.out.println("Prenotazione e cancellazione completate.");
    }
}
