/*
 * This source file was generated by the Gradle 'init' task
 */
//package sicurezza;
import java.util.HashMap;
import java.util.Scanner;

class Utente {
    private String username;
    private String password;

    public Utente(String username, String password) {
        this.username = username;
        this.password = password;
    }

    public String getUsername() { return username; }
    public String getPassword() { return password; }
}

public class App {
    public static void main(String[] args) {
        HashMap<String, Utente> utenti = new HashMap<>();
        Scanner scanner = new Scanner(System.in);

        while (true) {
            System.out.println("1. Registrazione");
            System.out.println("2. Login");
            System.out.println("3. Esci");
            System.out.print("Scegli un'opzione: ");
            int scelta = scanner.nextInt();
            scanner.nextLine(); // Consuma il newline

            if (scelta == 1) {
                System.out.print("Inserisci username: ");
                String username = scanner.nextLine();
                if (utenti.containsKey(username)) {
                    System.out.println("Username già esistente.");
                    continue;
                }
                System.out.print("Inserisci password: ");
                String password = scanner.nextLine();
                utenti.put(username, new Utente(username, password));
                System.out.println("Registrazione completata!");
            } else if (scelta == 2) {
                System.out.print("Inserisci username: ");
                String username = scanner.nextLine();
                System.out.print("Inserisci password: ");
                String password = scanner.nextLine();
                Utente utente = utenti.get(username);
                if (utente != null && utente.getPassword().equals(password)) {
                    System.out.println("Login riuscito!");
                } else {
                    System.out.println("Credenziali errate.");
                }
            } else if (scelta == 3) {
                System.out.println("Uscita...");
                break;
            } else {
                System.out.println("Opzione non valida.");
            }
        }
        scanner.close();
    }
}
