/*
 * This source file was generated by the Gradle 'init' task
 */
package login;

import java.util.HashMap;

public class App {

    public static void main(String[] args) {
        HashMap<String, String> map = new HashMap<>();
        map.put("utente1", "password1");
        map.put("utente2", "password2");
        map.put("utente3", "password3");
        map.put("utente4", "password4");
        if(map.containsKey(args[0]) && map.get(args[0]).equals(args[1])) {
            System.out.println("Accesso eseguito con successo!");
        } 
        else {
            System.out.println("Utente o password errati!");
        }
    }
}
