/*
 * This source file was generated by the Gradle 'init' task
 */
package contatore;

class Contatore<T> {
    private Object[] array;
    private int countInt;
    private int countString;
    public Contatore(Object[] array) {
        this.array = array;
        this.countInt = 0;
        this.countString = 0;
    }
    public void conta() {
        for (Object obj : array) {
            if (obj instanceof Integer) {
                countInt++;
            } else if (obj instanceof String) {
                countString++;
            }
        }
        System.out.println("Interi: " + countInt);
        System.out.println("Stringhe: " + countString);
    }
}
public class App {

    public static void main(String[] args) {
        Object[] array1={1,"ciao",2.5,"hello",7,8,"parola",9.5};
        Object[] array2={8,"hola",3.14,"danke",17,"batman","simsalabim"};
        Contatore<Object> contatore1 = new Contatore<>(array1);
        Contatore<Object> contatore2 = new Contatore<>(array2);
        System.out.println("Array 1:");
        contatore1.conta();
        System.out.println("Array 2:");
        contatore2.conta();
        
    }
}
