/*
 * This source file was generated by the Gradle 'init' task
 */
package ordinealfabetico;

public class App {
    public String ordina(String[] parole) {
        for (int i = 0; i < parole.length - 1; i++) {
            for (int j = i + 1; j < parole.length; j++) {
                if (parole[i].compareTo(parole[j]) > 0) {
                    String temp = parole[i];
                    parole[i] = parole[j];
                    parole[j] = temp;
                }
            }
        }
        return String.join(", ", parole);
    }

    public static void main(String[] args) {
        String[] parole = {"cane", "gatto", "elefante", "delfino", "zebra", "ippopotamo"};
        System.out.println("Parole pre ordinamento:");
        for (String parola : parole) {
            System.out.println(parola);
        }
        System.out.println("\nParole ordinate in ordine alfabetico:");
        parole = new App().ordina(parole).split(", ");
        for (String parola : parole) {
            System.out.println(parola);
        }
    }
}
