/*
 * This source file was generated by the Gradle 'init' task
 */
package libri;

import java.util.ArrayList;

class Libro{
    private String titolo;
    private String autore;
    private int annoPubblicazione;
    public Libro(String titolo, String autore, int annoPubblicazione){
        this.titolo = titolo;
        this.autore = autore;
        this.annoPubblicazione = annoPubblicazione;
    }
    public String toString(){
        return "Titolo: " + titolo + ", Autore: " + autore + ", Anno di pubblicazione: " + annoPubblicazione;
    }
}
public class App {

    public static void main(String[] args) {
        ArrayList<Libro> libri = new ArrayList<>();
        libri.add(new Libro("Il Signore degli Anelli", "J.R.R. Tolkien", 1954));
        libri.add(new Libro("1984", "George Orwell", 1949));
        libri.add(new Libro("Il Grande Gatsby", "F. Scott Fitzgerald", 1925));

        for (Libro libro : libri) {
            System.out.println(libro);
        }
    }
}
