/*
 * This source file was generated by the Gradle 'init' task
 */
package diario;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

class VoceDiario {
    private LocalDate data;
    private String testo;

    public VoceDiario(LocalDate data, String testo) {
        this.data = data;
        this.testo = testo;
    }

    public LocalDate getData() {
        return data;
    }

    public String getTesto() {
        return testo;
    }
}
public class App {

    public static void main(String[] args) {
        List<VoceDiario> diario = new ArrayList<>();
        diario.add(new VoceDiario(LocalDate.of(2025, 1, 1), "Oggi è una bella giornata."));
        diario.add(new VoceDiario(LocalDate.of(2025, 2, 2), "Ho iniziato a leggere un nuovo libro."));
        diario.add(new VoceDiario(LocalDate.of(2025, 4, 28), "Sono andato a correre nel parco."));
        diario.add(new VoceDiario(LocalDate.of(2025, 4, 25), "Ho cucinato una nuova ricetta."));
        
        for (VoceDiario voce : diario) {
            if(voce.getData().isAfter(LocalDate.now().minusDays(7))) {
                System.out.println("Data: " + voce.getData() + ", Testo: " + voce.getTesto());
            }
        }
    }
}
