/*
 * This source file was generated by the Gradle 'init' task
 */
package dadi;

class Giocatore{
    private final String nome;
    private int punteggio;

    public Giocatore(String nome) {
        this.nome = nome;
        this.punteggio = 0;
    }

    public String getNome() {
        return nome;
    }

    public int getPunteggio() {
        return punteggio;
    }

    public void setPunteggio(int punteggio) {
        this.punteggio = punteggio;
    }
}
public class App {
    public int lancioDadi(){
        int punteggio = 0;
        for (int i = 0; i < 3; i++) {
            punteggio += Math.floor(Math.random() * 6) + 1;
        }
        return punteggio;
    }

    public static void main(String[] args) {
        App app = new App();
        Giocatore giocatore1 = new Giocatore("Giocatore 1");
        Giocatore giocatore2 = new Giocatore("Giocatore 2");
        for (int i = 0; i < 5; i++) {
            giocatore1.setPunteggio(giocatore1.getPunteggio() + app.lancioDadi());
            giocatore2.setPunteggio(giocatore2.getPunteggio() + app.lancioDadi());
        }
        if(giocatore1.getPunteggio()> giocatore2.getPunteggio()){
            System.out.println(giocatore1.getNome() + " ha vinto con " + giocatore1.getPunteggio() + " punti");
        }
        else{
            System.out.println(giocatore2.getNome() + " ha vinto con " + giocatore2.getPunteggio() + " punti");
        }
    }
}
