/*
 * This source file was generated by the Gradle 'init' task
 */
package ordini;

import java.util.List;

interface Spedibile{
    public void spedizione();
}
class OrdineOnline implements  Spedibile{
    private String nome;
    private String cognome;
    private String indirizzo;
    private String telefono;
    private String email;

    public OrdineOnline(String nome, String cognome, String indirizzo, String telefono, String email) {
        this.nome = nome;
        this.cognome = cognome;
        this.indirizzo = indirizzo;
        this.telefono = telefono;
        this.email = email;
    }

    public void spedizione(){
        System.out.println("Ordine online effettuato.");
    }
}
class OrdineNegozio implements Spedibile{
    private String nome;
    private String cognome;
    private String indirizzo;
    private String telefono;
    private String email;

    public OrdineNegozio(String nome, String cognome, String indirizzo, String telefono, String email) {
        this.nome = nome;
        this.cognome = cognome;
        this.indirizzo = indirizzo;
        this.telefono = telefono;
        this.email = email;
    }

    public void spedizione(){
        System.out.println("Ordine in negozio effettuato.");
    }
}
public class App {
    public static void main(String[] args) {
        List<Spedibile> ordini = List.of(
            new OrdineOnline("Mario", "Rossi", "Via Roma 1", "1234567890", "dominio@email.com"),
            new OrdineNegozio("Luigi", "Verdi", "Via Milano 2", "0987654321", "admin@email.it")
        );
        for (Spedibile ordine : ordini) {
            ordine.spedizione();
        }
    }
}
