/*
 * This source file was generated by the Gradle 'init' task
 */

package battaglianavale;

import java.util.Random;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        final int SIZE = 5;
        final int NUM_SHIPS = 3;
        char[][] grid = new char[SIZE][SIZE];
        boolean[][] ships = new boolean[SIZE][SIZE];
        int shipsLeft = NUM_SHIPS;

        // Inizializza la griglia
        for (int i = 0; i < SIZE; i++)
            for (int j = 0; j < SIZE; j++)
                grid[i][j] = '.';

        // Posiziona le navi casualmente
        Random rand = new Random();
        int placed = 0;
        while (placed < NUM_SHIPS) {
            int x = rand.nextInt(SIZE);
            int y = rand.nextInt(SIZE);
            if (!ships[x][y]) {
                ships[x][y] = true;
                placed++;
            }
        }

        Scanner scanner = new Scanner(System.in);

        System.out.println("Benvenuto alla Battaglia Navale 5x5!");
        while (shipsLeft > 0) {
            // Mostra la griglia
            System.out.println("\nGriglia:");
            for (int i = 0; i < SIZE; i++) {
                for (int j = 0; j < SIZE; j++) {
                    System.out.print(grid[i][j] + " ");
                }
                System.out.println();
            }

            // Chiedi coordinate
            System.out.print("Inserisci riga (0-4): ");
            int row = scanner.nextInt();
            System.out.print("Inserisci colonna (0-4): ");
            int col = scanner.nextInt();

            if (row < 0 || row >= SIZE || col < 0 || col >= SIZE) {
                System.out.println("Coordinate non valide. Riprova.");
                continue;
            }

            if (grid[row][col] != '.') {
                System.out.println("Hai già provato queste coordinate. Riprova.");
                continue;
            }

            if (ships[row][col]) {
                System.out.println("Colpito!");
                grid[row][col] = 'X';
                shipsLeft--;
            } else {
                System.out.println("Mancato.");
                grid[row][col] = 'O';
            }
        }

        System.out.println("Complimenti! Hai affondato tutte le navi!");
        scanner.close();
    }
}
