/*
 * This source file was generated by the Gradle 'init' task
 */
package negozio;
import java.util.ArrayList;

class Prodotto {
    private String nome;
    private double prezzo;
    Prodotto(String nome, double prezzo) {
        this.nome = nome;
        this.prezzo = prezzo;
    }
    @Override
    public String toString(){
        return "Prodotto [nome=" + nome + ", prezzo=" + prezzo + "]";
    }
}
class Cliente {
    private String nome;
    private String cognome;
    private ArrayList<Prodotto> carrello = new ArrayList<>();
    private ArrayList<Ordine> ordini = new ArrayList<>();
    Cliente(String nome, String cognome) {
        this.nome = nome;
        this.cognome = cognome;
    }
    void aggiungiProdottoCarrello(Prodotto prodotto) {
        carrello.add(prodotto);
    }
    void rimuoviProdottoCarrello(Prodotto prodotto) {
        carrello.remove(prodotto);
    }
    void effettuaOrdine(Prodotto prodotto, int quantita) {
        Ordine ordine = new Ordine(prodotto, this, quantita);
        ordini.add(ordine);
    }
    void compraCarrello() {
        for (Prodotto prodotto : carrello) {
            Ordine ordine = new Ordine(prodotto, this, 1);
            ordini.add(ordine);
        }
        carrello.clear();
    }
    void visualizzaOrdini() {
        for (Ordine ordine : ordini) {
            System.out.println("Ordine: " + ordine.Visualizza());
        }
    }
    void visualizzaCarrello() {
        for (Prodotto prodotto : carrello) {
            System.out.println("Prodotto nel carrello: " + prodotto.toString());
        }
    }
}
class Ordine {
    private Prodotto prodotto;
    private Cliente cliente;
    private int quantita;
    Ordine(Prodotto prodotto, Cliente cliente, int quantita) {
        this.prodotto = prodotto;
        this.cliente = cliente;
        this.quantita = quantita;
    }
    String Visualizza() {
        return "Ordine [prodotto=" + prodotto.toString() + ", cliente=" + cliente + ", quantita=" + quantita + "]";
    }
}
public class App {
    

    public static void main(String[] args) {
        Cliente cliente1 = new Cliente( "Marco", "Rossi");
        Prodotto prodotto1 = new Prodotto("Laptop", 1200.00);
        Prodotto prodotto2 = new Prodotto("Smartphone", 800.00);
        Prodotto prodotto3 = new Prodotto("Tablet", 400.00);
        cliente1.aggiungiProdottoCarrello(prodotto1);
        cliente1.aggiungiProdottoCarrello(prodotto2);
        cliente1.visualizzaCarrello();
        cliente1.rimuoviProdottoCarrello(prodotto1);
        cliente1.effettuaOrdine(prodotto2, 2);
        cliente1.compraCarrello();
        cliente1.visualizzaOrdini();
    }
}
