/*
 * This source file was generated by the Gradle 'init' task
 */
package dipendenti;


import java.util.ArrayList;
import java.util.List;


abstract class Dipendente{
    private String nome;
    private float stipendio;
    Dipendente(String nome, float stipendio){
        this.nome = nome;
        this.stipendio = stipendio;
    }
    String getNome(){
        return nome;
    }
    abstract float calcolaStipendio();
}
class Impiegato extends Dipendente{
    private String nome;
    private float stipendio;
    Impiegato(String nome, float stipendio){
        super(nome, stipendio);
        this.nome = nome;
        this.stipendio = stipendio;
    }
    @Override
    float calcolaStipendio() {
        return stipendio;
    }
    String getNome(){
        return nome;
    }
}
class Manager extends Dipendente{
    private String nome;
    private float stipendio;
    private float bonus;
    Manager(String nome, float stipendio, float bonus){
        super(nome, stipendio);
        this.nome = nome;
        this.stipendio = stipendio;
        this.bonus = bonus;
    }
    @Override
    float  calcolaStipendio() {
        return stipendio+bonus;
    }
    String getNome(){
        return nome;
    }
}
class Azienda {
    private List<Dipendente> dipendenti;
    Azienda(List<Dipendente> dipendenti) {
        this.dipendenti = dipendenti;
    }
    void aggiungiDipendente(Dipendente dipendente) {
        dipendenti.add(dipendente);
    }
}
public class GestioneDipendenti{
    public static void main(String[] args) {
        List<Dipendente> dipendenti = new ArrayList();
        dipendenti.add(new Impiegato("Mario", 2000));
        dipendenti.add(new Manager("Luigi", 3000, 500));
        Azienda azienda = new Azienda(dipendenti);
        azienda.aggiungiDipendente(new Impiegato("Giovanni", 2500));
        for (Dipendente dipendente : dipendenti) {
            System.out.println("Stipendio di "+dipendente.getNome()+": "+dipendente.calcolaStipendio());
        }
    }
}
