/*
 * This source file was generated by the Gradle 'init' task
 */
package rubrica;

import java.util.ArrayList;
class Contatto {
    private String nome;
    private String numero;

    public Contatto(String nome, String numero) {
        this.nome = nome;
        this.numero = numero;
    }

    public String getNome() {
        return nome;
    }

    public String getNumero() {
        return numero;
    }
    public void setNome(String nome) {
        this.nome = nome;
    }
    public void setNumero(String numero) {
        this.numero = numero;
    }
}

public class Rubrica {

    public static void main(String[] args) {
        ArrayList<Contatto> rubrica = new ArrayList<>();
        rubrica.add(new Contatto("Luca", "123456789"));
        rubrica.add(new Contatto("Pigi", "987654321"));
        rubrica.add(new Contatto("Matilde", "456789123"));
        rubrica.get(3).setNome("Anna");
        rubrica.get(3).setNumero("321654987");
        for (Contatto contatto : rubrica) {
            System.out.println("Nome: " + contatto.getNome() + ", Numero: " + contatto.getNumero());
        }
    }
}
