/*
 * This source file was generated by the Gradle 'init' task
 */
package contatto;

import java.util.List;
import java.util.Scanner;

class Contatto{
    private String nome;
    private String numeroTelefono;
    private String email;

    public Contatto(String nome, String email, String numeroTelefono) {
        this.nome = nome;
        this.email = email;
        this.numeroTelefono = numeroTelefono;
    }

    public String getNome() {
        return nome;
    }

    public String getemail() {
        return email;
    }

    public String getNumeroTelefono() {
        return numeroTelefono;
    }
}
public class App {
    public static void main(String[] args) {
        List<Contatto> contatti = List.of(
                new Contatto("Mario Rossi", "mario.rossi@email.com", "1234567890"),
                new Contatto("Luigi Bianchi", "luigi.bianchi@email.com", "0987654321"));
        Scanner scanner = new Scanner(System.in);
        System.out.println("Inserisci la parola chiave per cercare i contatti:");
        String keyword = scanner.nextLine();
        List<Contatto> risultati = contatti.stream()
                .filter(contatto -> contatto.getNome().toLowerCase().contains(keyword.toLowerCase()))
                .toList();
        for (Contatto contact : risultati) {
            System.out.println("Nome: " + contact.getNome());
            System.out.println("Email: " + contact.getemail());
            System.out.println("Numero di telefono: " + contact.getNumeroTelefono());
            System.out.println("------------------------------");
        }
    }
}
