/*
 * This source file was generated by the Gradle 'init' task
 */
package registro;

import java.util.ArrayList;

class Studente{
    private String nome;
    private int matricola;
    private int voti[];
    public Studente(String nome, int matricola, int voti[]){
        this.nome = nome;
        this.matricola = matricola;
        this.voti = voti;
    }
    public String getNome() {
        return nome;
    }
    public int getMatricola() {
        return matricola;
    }
    public int[] getVoti() {
        return voti;
    }

}
public class App {

    public static void main(String[] args) {
        ArrayList<Studente> studenti = new ArrayList<>();
        studenti.add(new Studente("Mario Rossi", 12345, new int[]{28, 30, 25}));
        studenti.add(new Studente("Luigi Bianchi", 67890, new int[]{18, 20, 22}));
        studenti.add(new Studente("Giulia Verdi", 54321, new int[]{30, 30, 30}));
        for (Studente studente : studenti) {
            System.out.println("Nome: " + studente.getNome());
            System.out.println("Matricola: " + studente.getMatricola());
            System.out.print("Voti: ");
            for (int voto : studente.getVoti()) {
                System.out.print(voto + " ");
            }
            System.out.println();
        }
    }
}
