/*
 * This source file was generated by the Gradle 'init' task
 */
package eventi;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Scanner;


class Evento implements Comparable<Evento> {
    private String nome;
    private LocalDate data;
    private String luogo;

    public Evento(String nome, LocalDate data, String luogo) {
        this.nome = nome;
        this.data = data;
        this.luogo = luogo;
    }

    public String getNome() {
        return nome;
    }

    public LocalDate getData() {
        return data;
    }

    public String getLuogo() {
        return luogo;
    }

    @Override
    public int compareTo(Evento altro) {
        return this.data.compareTo(altro.data);
    }

    @Override
    public String toString() {
        return nome + " - " + data + " - " + luogo;
    }
}
public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        ArrayList<Evento> eventi = new ArrayList<>();

        while (true) {
            System.out.println("\n1. Aggiungi evento\n2. Visualizza eventi\n3. Esci");
            System.out.print("Scelta: ");
            int scelta = scanner.nextInt();
            scanner.nextLine(); // Consuma newline
            switch (scelta) {
                case 1 -> {
                    System.out.print("Nome evento: ");
                    String nome = scanner.nextLine();
                    System.out.print("Data evento (YYYY-MM-DD): ");
                    String dataStr = scanner.nextLine();
                    LocalDate data = LocalDate.parse(dataStr);
                    System.out.print("Luogo evento: ");
                    String luogo = scanner.nextLine();
                    eventi.add(new Evento(nome, data, luogo));
                    System.out.println("Evento aggiunto!");
                }
                case 2 -> {
                    Collections.sort(eventi);
                    System.out.println("\nEventi in ordine cronologico:");
                    for (Evento e : eventi) {
                        System.out.println(e);
                    }
                }
                case 3 -> {
                    scanner.close();
                    return;
                }
                default -> System.out.println("Scelta non valida.");
            }
        }
    }
}
