/*
 * This source file was generated by the Gradle 'init' task
 */
package libreria;

import java.util.ArrayList;
import java.util.Arrays;

class Libro{
    private String titolo;
    private String autore;
    private String isbn;
    private int annoPubblicazione;
    private String[] genere;

    public Libro(String titolo, String autore, String isbn, int annoPubblicazione, String[] genere) {
        this.titolo = titolo;
        this.autore = autore;
        this.isbn = isbn;
        this.annoPubblicazione = annoPubblicazione;
        this.genere = genere;
    }
    public String getTitolo() {
        return titolo;
    }
    public String getAutore() {
        return autore;
    }
    public String getIsbn() {
        return isbn;
    }
    public int getAnnoPubblicazione() {
        return annoPubblicazione;
    }
    public String[] getGenere() {
        return genere;
    }
}
public class App {

    public static void main(String[] args) {
        ArrayList<Libro> libreria = new ArrayList<>();
        libreria.add(new Libro("Il Signore degli Anelli", "J.R.R. Tolkien", "978-0261102385", 1954, new String[]{"Fantasy", "Adventure"}));
        libreria.add(new Libro("1984", "George Orwell", "978-0451524935", 1949, new String[]{"Dystopian", "Science Fiction"}));
        libreria.add(new Libro("Il Codice Da Vinci", "Dan Brown", "978-0307474278", 2003, new String[]{"Thriller", "Mystery"}));
        libreria.add(new Libro("Harry Potter e la Pietra Filosofale", "J.K. Rowling", "978-0747532699", 1997, new String[]{"Fantasy", "Adventure"}));
        libreria.add(new Libro("Il Nome della Rosa", "Umberto Eco", "978-8807880847", 1980, new String[]{"Historical Fiction", "Mystery"}));
        libreria.add(new Libro("Il Grande Gatsby", "F. Scott Fitzgerald", "978-0743273565", 1925, new String[]{"Classic", "Fiction"}));
        libreria.add(new Libro("Moby Dick", "Herman Melville", "978-1503280786", 1851, new String[]{"Adventure", "Classic"}));
        libreria.add(new Libro("Orgoglio e Pregiudizio", "Jane Austen", "978-1503290563", 1813, new String[]{"Romance", "Classic"}));
        
        //Simulazione di ricerca
        String[] filtri = new String[5];
        filtri[0] = "";
        filtri[1] = "J.R.R. Tolkien";
        filtri[2] = "";
        filtri[3] = "";
        filtri[4] = "Dystopian";
        // Ricerca dei libri in base ai filtri
        ArrayList<Libro> ricerca= new ArrayList<>();
        for (int i = 0; i < libreria.size(); i++) {
            Libro libro = libreria.get(i);
            if (libro.getAutore().equals(filtri[1]) || libro.getTitolo().equals(filtri[0]) || libro.getIsbn().equals(filtri[2]) || String.valueOf(libro.getAnnoPubblicazione()).equals(filtri[3]) || Arrays.asList(libro.getGenere()).contains(filtri[4])) {
                ricerca.add(libro);
            }
        }
        System.out.println("Libri trovati:");
        for (int i = 0; i < ricerca.size(); i++) {
            Libro book = ricerca.get(i);
            System.out.println("Titolo: " + book.getTitolo());
            System.out.println("Autore: " + book.getAutore());
            System.out.println("ISBN: " + book.getIsbn());
            System.out.println("Anno di pubblicazione: " + book.getAnnoPubblicazione());
            System.out.println("Genere: " + Arrays.toString(book.getGenere()));
            System.out.println();
        }
    }
}
