/*
 * This source file was generated by the Gradle 'init' task
 */
package magazzino;

import java.util.ArrayList;
import java.util.List;

abstract class Prodotto {
    protected String nome;
    protected  String codice;
    protected  double prezzo;
}
class Alimentare extends Prodotto {
    private String scadenza;

    public Alimentare(String nome,String codice, double prezzo,String scadenza) {
        this.nome = nome;
        this.codice = codice;
        this.prezzo = prezzo;
        this.scadenza = scadenza;
    }
    
}
class Elettronico extends Prodotto {
    private String marca;
    public Elettronico(String nome,String codice, double prezzo,String marca) {
        this.nome = nome;
        this.codice = codice;
        this.prezzo = prezzo;
        this.marca = marca;
    }
}
public class App {

    public static void main(String[] args) {
        ArrayList<Prodotto> prodotti = new ArrayList<>();
        prodotti.add(new Alimentare("Pasta", "001", 1.50, "2023-12-31"));
        prodotti.add(new Elettronico("Telefono", "002", 299.99, "Samsung"));
        prodotti.add(new Alimentare("Riso", "003", 2.00, "2024-01-15"));
        prodotti.add(new Elettronico("Laptop", "004", 999.99, "Dell"));
        for (Prodotto prodotto : prodotti) {
            if (prodotto instanceof Alimentare) {
                System.out.println(prodotto.nome+" e' un prodotto alimentare");
            } else if (prodotto instanceof Elettronico) {
                System.out.println(prodotto.nome+" e' un prodotto elettronico");
            }
        }
    }
}
