/*
 * This source file was generated by the Gradle 'init' task
 */
package somma;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.println("Inserisci un numero:");
        int number = scanner.nextInt();
        System.out.println("Inserisci un altro numero:");
        int number2 = scanner.nextInt();
        System.out.println("La somma è: " + (number+number2));
        scanner.close();
    }
}
