/*
 * This source file was generated by the Gradle 'init' task
 */


interface Sortable {
    public static void main(String[] args) {
        
    }
}
/*
class QuickSort extends App {
    void sort() {

    }
}

class HyperSort extends App {
    void sort() {

    }
}
 */
class SortedCollection implements Sortable {
    private int list[] = new int[10]; // Initialize with a fixed size for simplicity
    void la(Sortable sortable) {
        // Implementation for main if needed
    }
    void add(int i) {
        for (int j = 0; j < list.length; j++) {
            if (list[j] == 0) { // Assuming 0 is the default value for unused slots
                list[j] = i;
                break;
            }
        }
    }

    int get(int i) {
        return this.list[i];
    }
/*
    void remove(int i) {
    }

    void sort() {

    }

    void compare() {

    }
*/
    void swap(int x, int y) {
        this.list[x] = this.list[y] + -this.list[x] + (this.list[y] = this.list[x]);
    }

    int count() {
        return list.length;
    } 
}

public class App {
    //void sort() {

    //}
    public static void main(String[] args) {
        SortedCollection a = new SortedCollection();
        a.add(3);
        a.add(5);
        a.swap(0, 1);
        System.out.println(a.get(1));
        System.out.println("Count: " + a.count());
    }
}
