/*
 * This source file was generated by the Gradle 'init' task
 */
package scacchiera;
import java.util.Scanner;
class Scacchiera{
    private String[][] scacchiera={
        {"8. |", "r|","n|","b|","q|","k|","b|","n|","r|"},
        {"7. |", "p|","p|","p|","p|","p|","p|","p|","p|"},
        {"6. |", " |"," |"," |"," |"," |"," |"," |"," |"},
        {"5. |", " |"," |"," |"," |"," |"," |"," |"," |"},
        {"4. |", " |"," |"," |"," |"," |"," |"," |"," |"},
        {"3. |", " |"," |"," |"," |"," |"," |"," |"," |"},
        {"2. |", "P|","P|","P|","P|","P|","P|","P|","P|"},
        {"1. |", "R|","N|","B|","Q|","K|","B|","N|","R|"},
        {"   ", " a", " b", " c", " d", " e", " f", " g", " h"},
    };
    public String[][] getScacchiera() {
        return scacchiera;
    }
    public void muovi(String from, String to) {
        int fromRow = 8 - Integer.parseInt(from.substring(1, 2));
        int fromCol = from.charAt(0) - 'a' + 1;
        int toRow = 8 - Integer.parseInt(to.substring(1, 2));
        int toCol = to.charAt(0) - 'a' + 1;
        String piece = scacchiera[fromRow][fromCol];
        scacchiera[toRow][toCol] = piece;
        scacchiera[fromRow][fromCol] = " |";
    }
}
public class App {
    public static void main(String[] args) {
        Scacchiera scacchiera = new Scacchiera();
        for (int i = 0; i < 9; i++) {
            for (int j = 0; j < 9; j++) {
                System.out.print(scacchiera.getScacchiera()[i][j]);
            }
            System.out.println();
        }
        System.out.println("I pezzi bianchi sono rappresentati da lettere maiuscole e i pezzi neri da lettere minuscole.");
        System.out.println("I pezzi sono disposti in questo modo:");
        System.out.println("R/r = Torre; N/n = Cavallo; B/b = Alfiere; Q/q = Regina; K/k = Re; P/p = Pedone.");
        System.out.println("Per muovere un pezzo, inserire la casella in cui si trova il pezzo e la casella in cui si vuole muovere il pezzo./nAd esempio, per muovere il pedone in a2 in a4, inserire a2;a4.");
        Scanner scanner = new Scanner(System.in);
        String input;
        String[] inputSplit;
        String from;
        String to;
        System.out.println("Vuoi a muovere un pezzo? (s/n)");
        String risposta = scanner.nextLine();
        while (!risposta.equals("s") && !risposta.equals("n")) {
            System.out.println("Input non valido. Riprova.");
            risposta = scanner.nextLine();
        }
        while (risposta.equals("s")) {
            input = scanner.nextLine();
            while (!input.matches("[a-h][1-8];[a-h][1-8]")) {
                System.out.println("Input non valido. Riprova.");
                input = scanner.nextLine();
            }
            inputSplit = input.split(";");
            from = inputSplit[0];
            to = inputSplit[1];
            scacchiera.muovi(from, to);
            for (int i = 0; i < 9; i++) {
                for (int j = 0; j < 9; j++) {
                    System.out.print(scacchiera.getScacchiera()[i][j]);
                }
                System.out.println();
            }
            System.out.println("Il pezzo è stato spostato da " + from + " a " + to);
            System.out.println("Vuoi continuare a muovere? (s/n)");
            risposta = scanner.nextLine();
        }
        scanner.close();
    }
}
