/*
 * This source file was generated by the Gradle 'init' task
 */
package playlist;

import java.util.ArrayList;

class Canzone{
    private String titolo;
    private String artista;
    private int durata;

    public Canzone(String titolo, String artista, int durata) {
        this.titolo = titolo;
        this.artista = artista;
        this.durata = durata;
    }

    public String getTitolo() {
        return titolo;
    }

    public String getArtista() {
        return artista;
    }

    public int getDurata() {
        return durata;
    }
}
public class App {

    public static void main(String[] args) {
        ArrayList<Canzone> playlist = new ArrayList<>();
        playlist.add(new Canzone("Play That Funky Music", "Wild Cherry", 500));
        playlist.add(new Canzone("Grease", "Frankie Valli", 327));
        playlist.add(new Canzone("Come and Get Your Love", "Redbone", 325));
        playlist.add(new Canzone("Come On Eileen", "Dexys Midnight Runners", 447));
        playlist.add(new Canzone("Livin' On A Prayer", "Bon Jovi", 410));
        playlist.add(new Canzone("The Chain", "Fleetwood Mac", 430));
        playlist.add(new Canzone("Bad Case For Loving You (Doctor,Doctor)", "Robert Palmer", 315));
        playlist.add(new Canzone("Eye of the Tiger", "Survivor", 430));
        playlist.add(new Canzone("Burn It to the Ground", "Nickelback", 332));
        playlist.add(new Canzone("Boogie Wonderland", "Earth,Wind & Fire", 448));
        playlist.add(new Canzone("Old Time Rock & Roll", "Bob Seger", 314));
        playlist.add(new Canzone("Ain't No Mountain High Enough", "Marvin Gaye, Tammi Terrell", 231));
        playlist.add(new Canzone("Don't Stop Believin'", "Journey", 410));
        playlist.add(new Canzone("I Want You Back", "The Jackson 5", 256));

        int durataTotale = 0;
        for (Canzone canzone : playlist) {
            durataTotale += canzone.getDurata();
        }
        int minuti = durataTotale / 60;
        int secondi = durataTotale % 60;
        if(minuti > 60){
            int ore = minuti / 60;
            minuti = minuti % 60;
            System.out.println("La durata totale della playlist è di " + ore + " ore, " + minuti + " minuti e " + secondi + " secondi.");
        }else{
            System.out.println("La durata totale della playlist è di " + minuti + " minuti e " + secondi + " secondi.");
        }
    }
}
