/*
 * This source file was generated by the Gradle 'init' task
 */
package gara;

import java.util.ArrayList;

class Atleta{
    private String nome;
    private int tempoDiGara;

    Atleta(String nome,int tempoDiGara){
        this.tempoDiGara = tempoDiGara;
    }
    public int getTempoDiGara() {
        return tempoDiGara;
    }
}
public class App {
    static void ordina(ArrayList<Atleta> atleti){
        for (int i = 0; i < atleti.size(); i++) {
            for (int j = 0; j < atleti.size() - 1; j++) {
                if (atleti.get(j).getTempoDiGara() > atleti.get(j + 1).getTempoDiGara()) {
                    Atleta temp = atleti.get(j);
                    atleti.set(j, atleti.get(j + 1));
                    atleti.set(j + 1, temp);
                }
            }
        }
    }
    public static void main(String[] args) {
        ArrayList<Atleta> atleti = new ArrayList<>();
        atleti.add(new Atleta("Mario", 12));
        atleti.add(new Atleta("Luca", 34));
        atleti.add(new Atleta("Anna", 25));
        atleti.add(new Atleta("Sara", 49));

        for (Atleta atleta : atleti) {
            System.out.println(atleta.getTempoDiGara());
        }
        ordina(atleti);
        System.out.println("Dopo ordinamento:");
        for (Atleta atleta : atleti) {
            System.out.println(atleta.getTempoDiGara());
        }
    }
}
