/*
 * This source file was generated by the Gradle 'init' task
 */
package medico;

import java.util.ArrayList;
import java.util.List;

class Paziente{
    private String nome;
    private String cognome;
    private String codiceFiscale;
    public Paziente(String nome, String cognome, String codiceFiscale) {
        this.nome = nome;
        this.cognome = cognome;
        this.codiceFiscale = codiceFiscale;
    }
    public String getNome() {
        return nome;
    }
    public String getCognome() {
        return cognome;
    }
    public String getCodiceFiscale() {
        return codiceFiscale;
    }
}
class Medico{
    private String nome;
    private String cognome;
    private String specializzazione;
    public Medico(String nome, String cognome, String specializzazione) {
        this.nome = nome;
        this.cognome = cognome;
        this.specializzazione = specializzazione;
    }
    public String getNome() {
        return nome;
    }
    public String getCognome() {
        return cognome;
    }
    public String getSpecializzazione() {
        return specializzazione;
    }
}
class Visita{
    private Paziente paziente;
    private Medico medico;
    private String dataVisita;
    private String oraVisita;
    public Visita(Paziente paziente, Medico medico, String dataVisita, String oraVisita) {
        this.paziente = paziente;
        this.medico = medico;
        this.dataVisita = dataVisita;
        this.oraVisita = oraVisita;
    }
    public Paziente getPaziente() {
        return paziente;
    }
    public Medico getMedico() {
        return medico;
    }
    public String getDataVisita() {
        return dataVisita;
    }
    public String getOraVisita() {
        return oraVisita;
    }
}
public class App {

    public static void main(String[] args) {
        Paziente paziente = new Paziente("Mario", "Rossi", "RSSMRA80A01H501Z");
        Medico medico = new Medico("Giovanni", "Bianchi", "Cardiologia");
        Visita visita = new Visita(paziente, medico, "2023-10-01", "10:00");
        List<Visita> visite = new ArrayList<>();
        visite.add(visita);
        for (Visita i : visite) {
            if(i.getPaziente()==paziente){
                System.out.println("Visita trovata per il paziente: " + paziente.getNome() + " " + paziente.getCognome());
                System.out.println("La visita è il giorno: " + i.getDataVisita() + " alle ore: " + i.getOraVisita()+" con il medico: " + i.getMedico().getCognome() + " " + i.getMedico().getNome());
            }
            else{
                System.out.println("Visita non trovata per il paziente: " + paziente.getNome() + " " + paziente.getCognome());
            }
        }
    }
}
