/*
 * This source file was generated by the Gradle 'init' task
 */
package astratta;

import java.util.ArrayList;

abstract class Forma {
    double area() {
        return 0;
    }
}
class Cerchio extends Forma {
    double raggio;
    Cerchio(double raggio) {
        this.raggio = raggio;
    }
    @Override
    double area() {
        return Math.PI * raggio * raggio;
    }
}
class Rettangolo extends Forma {
    double base;
    double altezza;
    Rettangolo(double base, double altezza) {
        this.base = base;
        this.altezza = altezza;
    }
    @Override
    double area() {
        return base * altezza;
    }
}
public class App {

    public static void main(String[] args) {
        ArrayList<Forma> forme = new ArrayList<>();
        forme.add(new Cerchio(5));
        forme.add(new Rettangolo(4, 6));
        for (Forma forma : forme) {
            System.out.println("Area: " + forma.area());
        }
    }
}
