/*
 * This source file was generated by the Gradle 'init' task
 */
package viaggi;

import java.util.List;

interface Prenotabile {
    void prenota();
}
abstract class Viaggio{
    protected String destinazione;
    protected float prezzo;
    protected boolean prenotato;
    protected String dataPartenza;
    protected String dataRitorno;
    void descrizione() {
        System.out.println("Viaggio verso " + destinazione + " al prezzo di " + prezzo + " euro.");
        System.out.println("Data di partenza: " + dataPartenza);
        System.out.println("Data di ritorno: " + dataRitorno);
    }
}
class ViaggioAereo extends Viaggio implements Prenotabile{
    private String compagniaAerea;
    private String numeroVolo;
    private int numeroPosto;

    public ViaggioAereo(String destinazione, float prezzo, String compagniaAerea, String numeroVolo, String dataPartenza, String dataRitorno, int numeroPosto) {
        this.destinazione = destinazione;
        this.prezzo = prezzo;
        this.compagniaAerea = compagniaAerea;
        this.numeroVolo = numeroVolo;
        this.dataPartenza = dataPartenza;
        this.dataRitorno = dataRitorno;
    }

    @Override
    public void prenota() {
        prenotato = true;
        System.out.println("Prenotazione effettuata per il volo " + numeroVolo);
    }
}
class ViaggioTreno extends Viaggio implements Prenotabile{
    private String compagniaFerroviaria;
    private String numeroTreno;

    public ViaggioTreno(String destinazione, float prezzo, String compagniaFerroviaria, String numeroTreno, String dataPartenza, String dataRitorno) {
        this.destinazione = destinazione;
        this.prezzo = prezzo;
        this.compagniaFerroviaria = compagniaFerroviaria;
        this.numeroTreno = numeroTreno;
        this.dataPartenza = dataPartenza;
        this.dataRitorno = dataRitorno;
    }

    @Override
    public void prenota() {
        prenotato = true;
        System.out.println("Prenotazione effettuata per il treno " + numeroTreno);
    }
}
class SistemaPrenotazioni{
    List<Viaggio> viaggi;
    public SistemaPrenotazioni(List<Viaggio> viaggi) {
        this.viaggi = viaggi;
    }
    public void prenotaViaggio(Prenotabile viaggio) {
        if(((Viaggio) viaggio).prenotato) {
            System.out.println("Il viaggio è già prenotato");
        }
        else{
            viaggio.prenota();
        }
    }
    public void mostraViaggi() {
        for (Viaggio viaggio : viaggi) {
            viaggio.descrizione();
        }
    }
}
public class GestioneViaggi {
    public static void main(String[] args) {
        ViaggioAereo volo1 = new ViaggioAereo("Roma", 100, "Alitalia", "AZ123", "2023-10-01", "2023-10-15", 100);
        ViaggioTreno treno1 = new ViaggioTreno("Milano", 50, "Trenitalia", "T123", "2023-10-05", "2023-10-20");

        SistemaPrenotazioni sistema = new SistemaPrenotazioni(List.of(volo1, treno1));
        sistema.mostraViaggi();
        sistema.prenotaViaggio(volo1);
        sistema.prenotaViaggio(treno1);
        sistema.prenotaViaggio(volo1); // prova a prenotare di nuovo
    }
}
