/*
 * This source file was generated by the Gradle 'init' task
 */
package parcheggio;
class Auto {
    private String marca;
    private String modello;
    private String targa;

    public Auto(String marca, String modello, String targa) {
        this.marca = marca;
        this.modello = modello;
        this.targa = targa;
    }

    public String getMarca() {
        return marca;
    }

    public String getModello() {
        return modello;
    }

    public String getTarga() {
        return targa;
    }
}
class PostoAuto{
    private String nome;
    private int numeroPosto;
    private Auto auto;

    public PostoAuto(String nome, int numeroPosto) {
        this.nome = nome;
        this.numeroPosto = numeroPosto;
    }

    public String getNome() {
        return nome;
    }

    public int getNumeroPosto() {
        return numeroPosto;
    }

    public Auto getAuto() {
        return auto;
    }

    public void setAuto(Auto auto) {
        this.auto = auto;
        System.out.println("Auto " + auto.getMarca() + " " + auto.getModello() + " (" + auto.getTarga() + ") parcheggiata nel posto " + numeroPosto);
    }
    public void liberaPosto() {
        this.auto = null;
        System.out.println("Posto " + numeroPosto + " liberato");
    }
}
class Parcheggio{
    private String nome;
    private PostoAuto[] postiAuto;
    private int numeroPosti;
    private int postiOccupati=0;
    public Parcheggio(String nome, int numeroPosti) {
        this.nome = nome;
        this.numeroPosti = numeroPosti;
        this.postiAuto = new PostoAuto[numeroPosti];
        for (int i = 0; i < numeroPosti; i++) {
            postiAuto[i] = new PostoAuto(nome, i + 1);
        }
    }

    public String getNome() {
        return nome;
    }

    public PostoAuto[] getPostiAuto() {
        return postiAuto;
    }
}
public class App {

    public static void main(String[] args) {
        Parcheggio parcheggio = new Parcheggio("Parcheggio Centrale", 10);
        Auto auto1 = new Auto("Fiat", "Panda", "AB123CD");
        Auto auto2 = new Auto("Ford", "Fiesta", "EF456GH");
        Auto auto3 = new Auto("Toyota", "Yaris", "IJ789KL");
        parcheggio.getPostiAuto()[0].setAuto(auto1);
        parcheggio.getPostiAuto()[1].setAuto(auto2);
        parcheggio.getPostiAuto()[2].setAuto(auto3);
        System.out.println("Parcheggio: " + parcheggio.getNome());
        for (PostoAuto posto : parcheggio.getPostiAuto()) {
            if (posto.getAuto() != null) {
                System.out.println("Posto " + posto.getNumeroPosto() + ": " + posto.getAuto().getMarca() + " " + posto.getAuto().getModello() + " (" + posto.getAuto().getTarga() + ")");
            } else {
                System.out.println("Posto " + posto.getNumeroPosto() + ": Libero");
            }
        }
        parcheggio.getPostiAuto()[0].liberaPosto();
    }
}
