/*
 * This source file was generated by the Gradle 'init' task
 */
package votazione;

import java.util.Scanner;

class Votazione {
    private int[] voti;
    private int count;

    public Votazione(int maxVoti) {
        voti = new int[maxVoti];
        count = 0;
    }

    public void aggiungiVoto(int voto) {
        if (count < voti.length) {
            voti[count++] = voto;
        }
    }

    public double calcolaMedia() {
        if (count == 0) return 0;
        int somma = 0;
        for (int i = 0; i < count; i++) {
            somma += voti[i];
        }
        return (double) somma / count;
    }

    public int votoMassimo() {
        if (count == 0) return 0;
        int max = voti[0];
        for (int i = 1; i < count; i++) {
            if (voti[i] > max) max = voti[i];
        }
        return max;
    }

    public int votoMinimo() {
        if (count == 0) return 0;
        int min = voti[0];
        for (int i = 1; i < count; i++) {
            if (voti[i] < min) min = voti[i];
        }
        return min;
    }
}
public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.print("Quanti voti vuoi inserire? ");
        int n = scanner.nextInt();
        Votazione votazione = new Votazione(n);

        for (int i = 0; i < n; i++) {
            System.out.print("Inserisci il voto #" + (i + 1) + ": ");
            int voto = scanner.nextInt();
            votazione.aggiungiVoto(voto);
        }

        System.out.println("Media: " + votazione.calcolaMedia());
        System.out.println("Voto massimo: " + votazione.votoMassimo());
        System.out.println("Voto minimo: " + votazione.votoMinimo());

        scanner.close();
    }
}


