/*
 * This source file was generated by the Gradle 'init' task
 */
//package meteo;

import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Date;

class Previsione{
    private Date data;
    private String meteo;
    private int temperatura;

    public Previsione(Date data, String meteo, int temperatura) {
        this.data = data;
        this.meteo = meteo;
        this.temperatura = temperatura;
    }

    public Date getData() {
        return data;
    }

    public String getMeteo() {
        return meteo;
    }

    public int getTemperatura() {
        return temperatura;
    }
}
public class App {

    public static void main(String[] args) {
        ArrayList<Previsione> previsioni = new ArrayList<>();
        String[] meteo = {"Sereno", "Nuvoloso", "Piovoso", "Vento"};
        for (int i = 0; i < 10; i++) {
            int temp= (int) (Math.random() * 40)-10;
            String meteoRandom = meteo[(int) (Math.random() * meteo.length)];
            previsioni.add(new Previsione(new Date(), meteoRandom, temp));
        }
        Previsione maxTemp = new Previsione(new Date(), "Sereno", 0);
        Previsione minTemp = new Previsione(new Date(), "Sereno", 50);
        for (Previsione previsione : previsioni) {
            if (previsione.getTemperatura() > maxTemp.getTemperatura()) {
                maxTemp = previsione;
            }
            if (previsione.getTemperatura() < minTemp.getTemperatura()) {
                minTemp = previsione;
            }
        }
        
        System.out.println("Previsione con temperatura massima: " + maxTemp.getTemperatura() + "°C, meteo: " + maxTemp.getMeteo());
        System.out.println("Previsione con temperatura minima: " + minTemp.getTemperatura() + "°C, meteo: " + minTemp.getMeteo());
        System.out.println("Previsioni:");
        for (Previsione previsione : previsioni) {
            System.out.println("Data: " + previsione.getData() + ", Meteo: " + previsione.getMeteo() + ", Temperatura: " + previsione.getTemperatura() + "°C");
        }
    }
}
