/*
 * This source file was generated by the Gradle 'init' task
 */
package filtro;

public class App {

    public static void main(String[] args) {
        int[] array = {1, 2, 3, 4, 5, 6, 7, 8, 9};
        for (int i : array) {
            if (i % 2 == 0) {
                System.out.println(i);
            }
        }
    }
}
