/*
 * This source file was generated by the Gradle 'init' task
 */
package pagamenti;

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

interface Pagabile{
    public double effettuaPagamento(double importo);
}
abstract class MetodoPagamento{
    protected double saldoDisponibile;
}
class CartaDiCredito extends MetodoPagamento implements Pagabile{
    private String numeroCarta;
    private String intestatario;
    private String scadenza;
    private String cvv;
    public CartaDiCredito(String numeroCarta, String intestatario, String scadenza, String cvv){
        this.numeroCarta = numeroCarta;
        this.intestatario = intestatario;
        this.scadenza = scadenza;
        this.cvv = cvv;
    }
    public double effettuaPagamento(double importo){
        Scanner scanner = new Scanner(System.in);
        System.out.println("Inserisci il numero della carta di credito:");
        String inputnumeroCarta = scanner.nextLine();
        System.out.println("Inserisci il CVV:");
        String inputcvv = scanner.nextLine();
        System.out.println("Effettuando pagamento con carta di credito...");
        if(inputnumeroCarta.equals(numeroCarta) && inputcvv.equals(cvv)){
            try {
                if(saldoDisponibile >= importo){
                    saldoDisponibile -= importo;
                    return saldoDisponibile;
                } else {
                    throw new Exception("Saldo insufficiente");
                }
            } catch (Exception e) {
            }
        } else {
            System.out.println("Dati carta di credito non validi");
        }
        return saldoDisponibile;
    }
}
class PayPal extends MetodoPagamento implements Pagabile{
    private String email;
    private String password;
    public PayPal(String email, String password) {
        this.email = email;
        this.password = password;
    }
    public double effettuaPagamento(double importo){
        Scanner scanner = new Scanner(System.in);
        System.out.println("Inserisci l'email PayPal:");
        String inputEmail = scanner.nextLine();
        System.out.println("Inserisci la password:");
        String inputPassword = scanner.nextLine();
        System.out.println("Effettuando pagamento con PayPal...");
        if(inputEmail.equals(email) && inputPassword.equals(password)){
            try {
                if(saldoDisponibile >= importo){
                    saldoDisponibile -= importo;
                    return saldoDisponibile;
                } else {
                    throw new Exception("Saldo insufficiente");
                }
            } catch (Exception e) {
            }
        } else {
            System.out.println("Dati PayPal non validi");
        }
        return saldoDisponibile;
    }
}
class SistemiPagamenti{
    List<MetodoPagamento> metodiPagamento;
    public SistemiPagamenti(){
        metodiPagamento = new ArrayList<>();
    }
    public void aggiungiMetodoPagamento(MetodoPagamento metodo){
        metodiPagamento.add(metodo);
    }
    public void rimuoviMetodoPagamento(MetodoPagamento metodo){
        metodiPagamento.remove(metodo);
    }
    public void paga(double importo, Pagabile metodo){
        double saldo=metodo.effettuaPagamento(importo);
        System.out.println("Pagamento di " + importo + " effettuato. Saldo residuo: " + saldo);
    }
}
public class Pagamenti {
    public static void main(String[] args) {
        SistemiPagamenti sistemiPagamenti = new SistemiPagamenti();
        CartaDiCredito carta = new CartaDiCredito("1234567890123456", "Mario Rossi", "12/25", "123");
        PayPal paypal = new PayPal("mario.rossi@edu.unife.it", "password123");
        carta.saldoDisponibile = 1000;
        paypal.saldoDisponibile = 500;
        sistemiPagamenti.aggiungiMetodoPagamento(carta);
        sistemiPagamenti.aggiungiMetodoPagamento(paypal);
        sistemiPagamenti.paga(100, carta);
        sistemiPagamenti.paga(50, paypal);
        sistemiPagamenti.rimuoviMetodoPagamento(carta);
    }
}
