/*
 * This source file was generated by the Gradle 'init' task
 */
package calcolatrice;

public class App {
    public static void main(String[] args) {
        if (args.length != 3) {
            System.out.println("Uso corretto: <numero1> <operatore> <numero2>");
            System.out.println("Esempio: 3 + 5");
            return;
        }

        try {
            double num1 = Double.parseDouble(args[0]);
            String operatore = args[1];
            double num2 = Double.parseDouble(args[2]);

            double risultato = 0;

            switch (operatore) {
                case "+":
                    risultato = num1 + num2;
                    break;
                case "-":
                    risultato = num1 - num2;
                    break;
                case "*":
                    risultato = num1 * num2;
                    break;
                case "/":
                    if (num2 == 0) {
                        System.out.println("Non si può dividere per zero.");
                        return;
                    }
                    risultato = num1 / num2;
                    break;
                default:
                    System.out.println("Operatore non valido. Usa +, -, * o /.");
                    return;
            }

            System.out.println("Risultato: " + risultato);
        } catch (NumberFormatException e) {
            System.out.println("Errore: i numeri devono essere validi.");
        }
    }
}
