/*
 * This source file was generated by the Gradle 'init' task
 */
package scuola;

import java.util.ArrayList;

class Persona{
    private String nome;
    private String cognome;
    private int eta;

    public Persona(String nome, String cognome, int eta) {
        this.nome = nome;
        this.cognome = cognome;
        this.eta = eta;
    }

    public String getNome() {
        return nome;
    }

    public String getCognome() {
        return cognome;
    }

    public int getEta() {
        return eta;
    }
    public void setNome(String nome) {
        this.nome = nome;
    }
    public void setCognome(String cognome) {
        this.cognome = cognome;
    }
    public void setEta(int eta) {
        this.eta = eta;
    }
}
class Studente extends Persona{

    public Studente(String nome, String cognome, int eta) {
        super(nome, cognome, eta);
    }
}

class Insegnante extends Persona{

    public Insegnante(String nome, String cognome, int eta) {
        super(nome, cognome, eta);
    }
}
public class App {

    public static void main(String[] args) {
        ArrayList<Persona> persone = new ArrayList<>();
        persone.add(new Studente("Mario", "Rossi", 20));
        persone.add(new Insegnante("Giovanni", "Verdi", 40));
        persone.add(new Insegnante("Luca", "Bianchi", 35));
        persone.add(new Studente("Anna", "Neri", 20));
        persone.get(3).setCognome("Fregola");
        for (Persona persona : persone) {
            System.out.println("Nome: " + persona.getNome() + ", Cognome: " + persona.getCognome() + ", Età: " + persona.getEta());
        }
    }
}
