/*
 * This source file was generated by the Gradle 'init' task
 */
package biblioteca;

import java.util.ArrayList;
import java.util.List;

class Biblioteca extends MaterialeBibliotecario {
    private String nome;
    private String indirizzo;
    private List<MaterialeBibliotecario> listaMateriali;

    public Biblioteca(String nome, String indirizzo, List<MaterialeBibliotecario> listaMateriali) {
        super(nome, ""); // Pass 'nome' as titolo and an empty string as annoPubbicazione
        this.nome = nome;
        this.indirizzo = indirizzo;
        this.listaMateriali = listaMateriali;
    }

    public String getNome() {
        return nome;
    }

    public String getIndirizzo() {
        return indirizzo;
    }
    public void aggiungiMateriale(MaterialeBibliotecario materiale) {
        listaMateriali.add(materiale);
    }
    public void rimuoviMateriale(MaterialeBibliotecario materiale) {
        listaMateriali.remove(materiale);
    }
    public void stampaMateriali() {
        for (MaterialeBibliotecario materiale : listaMateriali) {
            System.out.println("Titolo: " + materiale.getTitle() + ", Anno di pubblicazione: " + materiale.getAnno());
        }
    }

}
class Libro extends MaterialeBibliotecario {
    public Libro(String titolo, String annoP) {
        super(titolo, annoP);
    }
}
class Rivista extends MaterialeBibliotecario{
    public Rivista(String titolo, String annoP) {
        super(titolo, annoP);
    }

}
abstract class MaterialeBibliotecario {
    private final String titolo;
    private final String annoPubbicazione;

    public MaterialeBibliotecario(String titolo, String annoP) {
        this.titolo = titolo;
        this.annoPubbicazione = annoP;
    }

    public String getTitle() {
        return titolo;
    }

    public String getAnno() {
        return annoPubbicazione;
    }
}
public class GestioneBiblioteca {
    public static void main(String[] args) {
        List<MaterialeBibliotecario> libri = new ArrayList<>();
        libri.add(new Libro("Il Signore degli Anelli", "1954"));
        libri.add(new Rivista("National Geographic", "2023"));
        libri.add(new Rivista("Percy Jackson", "2005"));
        Biblioteca biblioteca = new Biblioteca("Biblioteca Ariostea", "Via delle Scienze, 17", libri);
        biblioteca.stampaMateriali();
        biblioteca.aggiungiMateriale(new Libro("Harry Potter", "1997"));
        biblioteca.rimuoviMateriale(libri.get(1));
        System.out.println("Materiali dopo le modifiche:");
        biblioteca.stampaMateriali();
        System.out.println("Nome della biblioteca: " + biblioteca.getNome());
        System.out.println("Indirizzo della biblioteca: " + biblioteca.getIndirizzo());
        
    }
}
