/*
 * This source file was generated by the Gradle 'init' task
 */
package task;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;

class Task{
    private String descrizione;
    private int priorita;
    private String scadenza;

    public Task(String descrizione, int priorita, String scadenza) {
        this.descrizione = descrizione;
        this.priorita = priorita;
        this.scadenza = scadenza;
    }
    public String getDescrizione() {
        return descrizione;
    }
    public String getScadenza() {
        return scadenza;
    }
    public int getPriorita() {
        return priorita;
    }
    public String toString() {
        return "Descrizione: " + descrizione + ", Priorita: " + priorita + ", Scadenza: " + scadenza;
    }
}
public class App {

    public static void main(String[] args) {
        ArrayList<Task> elencoTask = new ArrayList<Task>();
        elencoTask.add(new Task("controllo collegamento elettrico", 5,"2023-10-01"));
        elencoTask.add(new Task("controllo collegamento idrico", 5,"2023-10-02"));
        elencoTask.add(new Task("controllo collegamento gas", 3,"2023-10-03"));
        elencoTask.add(new Task("controllo collegamento internet", 6,"2023-10-04"));
        elencoTask.add(new Task("controllo collegamento telefonico", 6,"2023-02-04"));
        elencoTask.add(new Task("controllo collegamento tv", 6,"2023-01-04"));
        elencoTask.add(new Task("controllo collegamento antifurto", 2,"2023-06-04"));
        elencoTask.add(new Task("controllo collegamento allarme", 3,"2023-10-24"));
        
        for (int i = 0; i < elencoTask.size() - 1; i++) {
            for (int j = 0; j < elencoTask.size() - i - 1; j++) {
                if (elencoTask.get(j).getPriorita() > elencoTask.get(j + 1).getPriorita()) {
                    Object temp = elencoTask.get(j);
                    elencoTask.set(j, elencoTask.get(j + 1));
                    elencoTask.set(j + 1, (Task) temp);
                }
                if(elencoTask.get(j).getPriorita() == elencoTask.get(j + 1).getPriorita()){
                    if(LocalDate.parse(elencoTask.get(j).getScadenza()).isAfter(LocalDate.parse(elencoTask.get(j + 1).getScadenza()))){
                        Object temp = elencoTask.get(j);
                        elencoTask.set(j, elencoTask.get(j + 1));
                        elencoTask.set(j + 1, (Task) temp);
                    }
                }
            }
        }
        for (int i = 0; i < elencoTask.size(); i++) {
            System.out.println(elencoTask.get(i).toString());
        }
    }
}
