/*
 * This source file was generated by the Gradle 'init' task
 */
package provaesame11_04;

import java.util.ArrayList;

interface Lavoratore{

}
interface Pagabile{

}
abstract class Dipendente implements Lavoratore, Pagabile{
    private String nome;
    Dipendente(String nome){
        this.nome = nome;
    }
    public String getNome() {
        return this.nome;
    }
}
class Manager extends Dipendente{
    private String mobile;
    Manager(String nome, String mobile){
        super(nome);
        this.mobile = mobile;
    }
    void lavora(){
        
    }
    double calcolaPaga(){
        return 0;
    }
}
class Sviluppatore extends Dipendente{
    private String matricola;
    Sviluppatore(String nome, String matricola){
        super(nome);
        this.matricola = matricola;
    }
    void lavora(){
        
    }
    double calcolaPaga(){
        return 0;
    }
}
public class App {
    

    public static void main(String[] args) {
        ArrayList<Dipendente> dipendenti = new ArrayList<>();
        for(int i = 0; i < 10; i++){
            dipendenti.add(new Sviluppatore("Name"+i, "Mat"+i));
        }
        dipendenti.add(new Manager("Manager", "Mobile10"));
        for(Dipendente d : dipendenti){
            d.calcolaPaga();
        }
    }
}