
/*
 * This source file was generated by the Gradle 'init' task
 */
package calcolatriceavanzata;
import java.util.Scanner;
abstract class Operazioni{
    private int a;
    private int b;
    abstract int calcola(int a, int b);
}
class Addizione extends Operazioni{
    int calcola(int a, int b) {
        return a + b;
    }
}
class Sottrazione extends Operazioni{
    int calcola(int a, int b) {
        return a - b;
    }
}
class Moltiplicazione extends Operazioni{
    int calcola(int a, int b) {
        return a * b;
    }
}
class Divisione extends Operazioni{
   int calcola(int a, int b) {
        if (b == 0) {
            throw new ArithmeticException("Divisione per zero non permessa");
        }
        return a / b;
    }
}
public class App {

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.println("Inserisci equazione da eseguire:");
        String eq=scanner.nextLine();
        scanner.close();
        String[] parts = eq.split(" ");
        int a = Integer.parseInt(parts[0]);
        String operatore = parts[1];
        int b = Integer.parseInt(parts[2]);
        Operazioni operazione = null;
        switch (operatore) {
            case "+":
                operazione = new Addizione();
                break;
            case "-":
                operazione = new Sottrazione();
                break;
            case "*":
                operazione = new Moltiplicazione();
                break;
            case "/":
                operazione = new Divisione();
                break;
            default:
                System.out.println("Operatore non valido");
                return;
        }
        try {
            int risultato = operazione.calcola(a, b);
            System.out.println("Risultato: " + risultato);
        } catch (ArithmeticException e) {
            System.out.println(e.getMessage());
        }
    }
}
