/*
 * This source file was generated by the Gradle 'init' task  {"nome":"Luca","eta":22}
 */
package parser;
class Persona{
    private String nome;
    private int eta;
    Persona(String nome, int eta) {
        this.nome = nome;
        this.eta = eta;
    }
    public String getNome() {
        return nome;
    }
    public int getEta() {
        return eta;
    }
}
public class App {
    public static void main(String[] args) {
        String[] person = args[0].replaceAll("[{}]", "").split(",");
        String nome = person[0].split(":")[1];
        int eta = Integer.parseInt(person[1].split(":")[1]);
        Persona p = new Persona(nome, eta);
        System.out.println("Nome: " + p.getNome());
        System.out.println("Età: " + p.getEta());
    }
}
